### ISSUE TITLE
cannot run in windows

### ISSUE THREAD

**Issue by skanehira** [skanehira/deno-clipboard-image#4]
PSVersion 5.1.19041.1151

```
PowerShell -Command Add-Type -AssemblyName System.Windows.Forms;[Windows.Forms.Clipboard]::SetImage([System.Drawing.Image]::FromFile('C:\Users\xxxx\AppData\Local\Temp\4fe4599d'));
error: Uncaught (in promise) Error: �^ [System.Drawing.Image] ��������܂���B
�����ꏊ �s:1 ����:81
+ ... ms;[Windows.Forms.Clipboard]::SetImage([System.Drawing.Image]::FromFi ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Drawing.Image:TypeName) []�ARuntimeException
    + FullyQualifiedErrorId : TypeNotFound


    throw new Error(new TextDecoder().decode(await p.stderrOutput()));
          ^
    at write (file:///C:/Users/xxxx/deno-clipboard-image/mod.ts:123:11)
    at async file:///C:/Users/xxxx/deno-clipboard-image/example/main.ts:9:3
```

**Comment by skanehira** [comment]
This version can run 

```
$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
